version: "2.0"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/web
      - logvolume01:/var/log      
    environment:
      - HOST=localhost
      - HOST_HTTPS=localhost:8000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    volumes:
      - .:/api
      - logvolume02:/var/log

volumes:
  logvolume01: {}
  logvolume02: {}
